version: '3'

tasks:
  build:
    cmds:
      - go build -ldflags "-w -s" -o api-backend.exe
  start:dev:
    cmds:
      - task: build
      - export ENVIRONMENT=development
      - api-backend.exe
    env:
      ENVIRONMENT: development
  start:prod:
    cmds:
      - task: build
      - export ENVIRONMENT=production
      - api-backend.exe
    env:
      ENVIRONMENT: production